"""Initial migration

Revision ID: 2ef58ffd845e
Revises: 
Create Date: 2024-03-04 13:42:00.912579

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ef58ffd845e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('serial_key', sa.Column('added_date', sa.DateTime(), nullable=True))
    op.create_unique_constraint(None, 'serial_key', ['key'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'serial_key', type_='unique')
    op.drop_column('serial_key', 'added_date')
    # ### end Alembic commands ###
